In [12]:
import sqlite3

connection = sqlite3.connect("./data/chinook.db")

In [13]:
import pandas as pd

pd.read_sql_query("SELECT * FROM sqlite_master WHERE type='table'", connection)

,type,name,tbl_name,rootpage,sql
0,table,Album,Album,2,CREATE TABLE [Album]\n(\n [AlbumId] INTEGER...
1,table,Artist,Artist,3,CREATE TABLE [Artist]\n(\n [ArtistId] INTEG...
2,table,Customer,Customer,4,CREATE TABLE [Customer]\n(\n [CustomerId] I...
3,table,Employee,Employee,7,CREATE TABLE [Employee]\n(\n [EmployeeId] I...
4,table,Genre,Genre,9,CREATE TABLE [Genre]\n(\n [GenreId] INTEGER...
5,table,Invoice,Invoice,10,CREATE TABLE [Invoice]\n(\n [InvoiceId] INT...
6,table,InvoiceLine,InvoiceLine,12,CREATE TABLE [InvoiceLine]\n(\n [InvoiceLin...
7,table,MediaType,MediaType,14,CREATE TABLE [MediaType]\n(\n [MediaTypeId]...
8,table,Playlist,Playlist,15,CREATE TABLE [Playlist]\n(\n [PlaylistId] I...
9,table,PlaylistTrack,PlaylistTrack,16,CREATE TABLE [PlaylistTrack]\n(\n [Playlist...
10,table,Track,Track,19,CREATE TABLE [Track]\n(\n [TrackId] INTEGER...

In [14]:
pd.read_sql("select * from Album", connection)

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [15]:
pd.read_sql("select * from Album", connection, index_col="AlbumId")

                                                     Title  ArtistId
AlbumId
1                    For Those About To Rock We Salute You         1
2                                        Balls to the Wall         2
3                                        Restless and Wild         2
4                                        Let There Be Rock         1
5                                                 Big Ones         3
...                                                    ...       ...
343                                 Respighi:Pines of Rome       226
344      Schubert: The Late String Quartets & String Qu...       272
345                                    Monteverdi: L'Orfeo       273
346                                  Mozart: Chamber Music       274
347      Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 2 columns]

In [16]:
pd.read_sql("select * from Invoice", connection)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99

In [17]:
def sq(str, con=connection):
    return pd.read_sql("""{}""".format(str), con)

In [18]:
sq(""" select * from Invoice where total > '10' """)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
1,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
2,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
3,26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86
4,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
...,...,...,...,...,...,...,...,...,...
59,383,10,2013-08-12 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,13.86
60,390,48,2013-09-12 00:00:00,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,13.86
61,397,27,2013-10-13 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,13.86
62,404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86
63,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86

In [24]:
sq(""" select *
   from invoice
   where total < (select avg(total) from invoice)
   """)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,6,37,2009-01-19 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,0.99
3,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
4,8,40,2009-02-01 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,1.98
...,...,...,...,...,...,...,...,...,...
228,405,20,2013-11-21 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,0.99
229,406,21,2013-12-04 00:00:00,801 W 4th Street,Reno,NV,USA,89503,1.98
230,407,23,2013-12-04 00:00:00,69 Salem Street,Boston,MA,USA,2113,1.98
231,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
232,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99

In [25]:
sq("""select * from Artist where name like 'D%' """)

   ArtistId                                Name
0        55                     David Coverdale
1        58                         Deep Purple
2        78                         Def Leppard
3        79                     Dennis Chambers
4        80                              Djavan
5       157                      Dread Zeppelin
6       164        Dhani Harrison & Jakob Dylan
7       192  DJ Dolores & Orchestra Santa Massa

In [26]:
sq("""select * from Album order by title asc""")

     AlbumId                                              Title  ArtistId
0        156                             ...And Justice For All        50
1        257  20th Century Masters - The Millennium Collecti...       179
2        296                      A Copland Celebration, Vol. I       230
3         94                         A Matter of Life and Death        90
4         95                                    A Real Dead One        90
..       ...                                                ...       ...
342        8                                     Warner 25 Anos         6
343      334                       Weill: The Seven Deadly Sins       264
344      267                                             Worlds       202
345      240                                            Zooropa       150
346      208                        [1997] Black Light Syndrome       136

[347 rows x 3 columns]

In [27]:
sq("""  SELECT * FROM album
   JOIN artist ON artist.artistid = album.artistid""")

,AlbumId,Title,ArtistId,ArtistId,Name
0,1,For Those About To Rock We Salute You,1,1,AC/DC
1,2,Balls to the Wall,2,2,Accept
2,3,Restless and Wild,2,2,Accept
3,4,Let There Be Rock,1,1,AC/DC
4,5,Big Ones,3,3,Aerosmith
...,...,...,...,...,...
342,343,Respighi:Pines of Rome,226,226,Eugene Ormandy
343,344,Schubert: The Late String Quartets & String Qu...,272,272,Emerson String Quartet
344,345,Monteverdi: L'Orfeo,273,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
345,346,Mozart: Chamber Music,274,274,Nash Ensemble
346,347,Koyaanisqatsi (Soundtrack from the Motion Pict...,275,275,Philip Glass Ensemble

In [29]:
sq("""  select album.albumid,
        album.title,
        artist.name
   from album
   JOIN artist ON artist.artistid = album.artistid """)

,AlbumId,Title,Name
0,1,For Those About To Rock We Salute You,AC/DC
1,2,Balls to the Wall,Accept
2,3,Restless and Wild,Accept
3,4,Let There Be Rock,AC/DC
4,5,Big Ones,Aerosmith
...,...,...,...
342,343,Respighi:Pines of Rome,Eugene Ormandy
343,344,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
344,345,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
345,346,Mozart: Chamber Music,Nash Ensemble
346,347,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

In [3]:
import sqlite3
import requests

url = "http://universities.hipolabs.com/search?country=Brazil"

response = requests.get(url)
response.raise_for_status()
universities = response.json()

In [4]:
universities[0]

{'name': 'Universidade Comunitária da Região de Chapecó - Unochapecó', 'state-province': None, 'alpha_two_code': 'BR', 'domains': ['unochapeco.edu.br'], 'country': 'Brazil', 'web_pages': ['https://unochapeco.edu.br']}

## Modelagem e Persistência dos Dados de Universidades

### Estrutura retornada pela API
Cada registro possui:
- `name`, `country`, `alpha_two_code`, `state-province` — campos escalares
- `domains`, `web_pages` — **listas** (um-para-muitos)

### Modelo relacional proposto

```
universities
  ├── id              INTEGER  PK AUTOINCREMENT
  ├── name            TEXT     NOT NULL
  ├── country         TEXT     NOT NULL
  ├── alpha_two_code  TEXT
  ├── state_province  TEXT
  └── extracted_at    TIMESTAMP  DEFAULT CURRENT_TIMESTAMP

university_domains
  ├── id              INTEGER  PK AUTOINCREMENT
  ├── university_id   INTEGER  FK → universities.id
  └── domain          TEXT

university_web_pages
  ├── id              INTEGER  PK AUTOINCREMENT
  ├── university_id   INTEGER  FK → universities.id
  └── web_page        TEXT
```

**Restrição de unicidade**: `UNIQUE(name, country)` em `universities` é a chave natural que evita duplicatas ao reprocessar países.

### Estratégia para múltiplos países

| Aspecto | Decisão |
|---|---|
| **Upsert** | `INSERT OR IGNORE` respeita a constraint e não sobrescreve dados existentes; use `INSERT OR REPLACE` se precisar atualizar |
| **Rastreabilidade** | `extracted_at` registra quando cada lote foi inserido |
| **Atomicidade** | Cada país é inserido dentro de uma **transação** — falha em um país não corrompe os demais |
| **Performance** | `executemany` + `commit` único por lote é muito mais rápido que commits individuais |
| **Índices** | Criar índice em `country` e `alpha_two_code` para consultas por país |

In [38]:
uni_conn = sqlite3.connect("./data/universities.db")
cur = uni_conn.cursor()

cur.executescript("""
    CREATE TABLE IF NOT EXISTS universities (
        id              INTEGER  PRIMARY KEY AUTOINCREMENT,
        name            TEXT     NOT NULL,
        country         TEXT     NOT NULL,
        alpha_two_code  TEXT,
        state_province  TEXT,
        extracted_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(name, country)
    );

    CREATE TABLE IF NOT EXISTS university_domains (
        id              INTEGER  PRIMARY KEY AUTOINCREMENT,
        university_id   INTEGER  NOT NULL REFERENCES universities(id),
        domain          TEXT     NOT NULL
    );

    CREATE TABLE IF NOT EXISTS university_web_pages (
        id              INTEGER  PRIMARY KEY AUTOINCREMENT,
        university_id   INTEGER  NOT NULL REFERENCES universities(id),
        web_page        TEXT     NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_uni_country      ON universities(country);
    CREATE INDEX IF NOT EXISTS idx_uni_alpha_two    ON universities(alpha_two_code);
    CREATE INDEX IF NOT EXISTS idx_domains_uni_id   ON university_domains(university_id);
    CREATE INDEX IF NOT EXISTS idx_webpages_uni_id  ON university_web_pages(university_id);
""")

uni_conn.commit()
print("Tabelas criadas com sucesso.")

Tabelas criadas com sucesso.

In [39]:
def persist_universities(records: list[dict], conn: sqlite3.Connection) -> int:
    """
    Insere (ou ignora duplicatas) um lote de universidades retornado pela API.
    Retorna o número de registros efetivamente inseridos.
    """
    cur = conn.cursor()
    inserted = 0

    for uni in records:
        cur.execute(
            """
            INSERT OR IGNORE INTO universities (name, country, alpha_two_code, state_province)
            VALUES (?, ?, ?, ?)
        """,
            (
                uni.get("name"),
                uni.get("country"),
                uni.get("alpha_two_code"),
                uni.get("state-province"),
            ),
        )

        if cur.rowcount == 0:
            continue

        uni_id = cur.lastrowid
        inserted += 1

        cur.executemany(
            "INSERT INTO university_domains (university_id, domain) VALUES (?, ?)",
            [(uni_id, d) for d in uni.get("domains", [])],
        )
        cur.executemany(
            "INSERT INTO university_web_pages (university_id, web_page) VALUES (?, ?)",
            [(uni_id, w) for w in uni.get("web_pages", [])],
        )

    conn.commit()
    return inserted


COUNTRIES = ["Brazil", "China", "Indonesia"]
BASE_URL = "http://universities.hipolabs.com/search?country={}"

for country in COUNTRIES:
    resp = requests.get(BASE_URL.format(country))
    resp.raise_for_status()
    data = resp.json()
    n = persist_universities(data, uni_conn)
    print(f"{country:12s} → {len(data):4d} registros na API | {n:4d} inseridos agora")

Brazil       →  190 registros na API |  190 inseridos agora
China        →  398 registros na API |  398 inseridos agora
Indonesia    →  192 registros na API |  192 inseridos agora

In [45]:
uni_pd = lambda sql: pd.read_sql(sql, uni_conn)

# Total por país
display(uni_pd("""
    SELECT country, alpha_two_code, COUNT(*) AS total_universities
    FROM universities
    GROUP BY country
    ORDER BY total_universities DESC
"""))

     country alpha_two_code  total_universities
0      China             CN                 398
1  Indonesia             ID                 192
2     Brazil             BR                 190

In [44]:
# Universidades com múltiplos domínios (JOIN com tabela filha)
display(uni_pd("""
    SELECT u.name, u.country, COUNT(d.id) AS domain_count
    FROM universities u
    JOIN university_domains d ON d.university_id = u.id
    GROUP BY u.id
    HAVING domain_count > 1
    ORDER BY domain_count DESC
    LIMIT 10
"""))

                                        name country  domain_count
0                           Instituto Infnet  Brazil             3
1       Polytechnic University of Pernambuco  Brazil             3
2                           Xihua University   China             3
3  Centro Universitário de Brasília, UNICEUB  Brazil             2
4          Universidade Católica de Salvador  Brazil             2
5       Universidade Federal de Minas Gerais  Brazil             2
6         Centro Universitário de Araraquara  Brazil             2
7                                    UNINOVE  Brazil             2
8                     Sun Yat-Sen University   China             2
9                           Hunan University   China             2